### ISSUE TITLE
Error when passing null as argumentsList to Reflect.construct

### ISSUE THREAD

**Issue by hakvroot** [dryajov/opium#1]
When a type is registered without any additional dependencies the ConstructorInjector's inject method fails in (at least) Firefox 44. This is because of the fact that null is passed to Reflect.construct in the [ConstructorInjector](https://github.com/dryajov/opium/blob/cbe4d68f58308ba65105fde97abbb351e5a78a80/app/scripts/injectors/constructor-injector.js)'s _newCall method. Per Mozilla's [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct) it should be given an array-like object or the value should be omitted in the call (the official ES 2015 spec is more vague about this). To quickly test it in your own browser (if Reflect is available) :

    Reflect.construct(Object, null); // should fail

    Reflect.construct(Object, []); // should succeed

 I already patched this myself and will send a pull request shortly.

**Comment by dryajov** [comment]
This is awesome! I'll get your pull request merged ASAP.

**Comment by hakvroot** [comment]
Thanks! And thanks for an awesome project too :)
